server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    username: vijayuidzephyr@gmail.com
    password: xrhs rwmp xdoi bcey
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  data:
    mongodb:
      auto-index-creation: 'true'
      database: journaldb
      uri: mongodb+srv://vijayuidzephyr:HlWm5jvxpat3UBjU@cluster0.wfiuv5m.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  application:
    name: JournalManagement
  devtools:
    restart:
      enabled: 'true'
logging:
  file:
    name: loggers.log
  level:
    com:
      vscode:
        springbootjournalappmongodb: DEBUG

POST_API: https://fakestoreapi.com/users



