server:
  port: 8080
spring:
  redis:
    host: localhost
    port: 6379
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.gmail.com
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  data:
    mongodb:
      auto-index-creation: 'true'
      database: journaldb
      uri: ${MongoDB_Atlas_Cloud_URL}
  application:
    name: JournalManagement
  devtools:
    restart:
      enabled: 'true'
  cloud:
    config:
      uri: http://localhost:8888
logging:
  file:
    name: loggers.log
  level:
    com:
      vscode:
        springbootjournalappmongodb: DEBUG

POST_API: https://fakestoreapi.com/users



